### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by raduchiriac** [sandeep1995/list-dep#1]
windows here (yeah, I know...)
node -v: v6.10.1
npm -v: 3.10.10

list-dep@1.0.2

> $ list
C:\Users\RADUCHI\AppData\Roaming\npm\node_modules\list-dep\index.js:65
                                        let package = `${val}&&${version}`;
                                            ^^^^^^^
SyntaxError: Unexpected identifier

**Comment by sandeep1995** [comment]
It's because the package is written in ES6. Can you install the latest nodejs and let me know if it's working or not?

[Download Nodejs](https://nodejs.org/en/download/)

**Comment by raduchiriac** [comment]
I think it's unrelated. 
ES6 is available since v4 (correct if wrong).

I am guessing he doesn't like the name `package`. I changed it to `apackage` and worked great.

**Comment by sandeep1995** [comment]
Does it make sense @raduchiriac? How can a variable name break codebase? Further investigation needed.

**Comment by raduchiriac** [comment]
Oh boy it can https://mothereff.in/js-variables
Just use something else but `package`

I can do it if you accept PR

**Comment by sandeep1995** [comment]
Great. Thanks for the link. Make one PR mentioning this issue.
